module Services
  class InventoryTransferSuggestionsResponse
    def self.call: (
        inventory_repo: Repositories::Inventory,
        logger: Logger,
        renderer: JSONAPI::Serializable::Renderer,
        ?success: Proc,
        ?error: Proc,
        ?params: Hash[Symbol, String | Integer],
        ?request: Hash[Symbol, untyped]
      ) -> untyped

    def call: () -> Proc

    private

    attr_reader inventory_repo: Repositories::Inventory

    attr_reader logger: Logger

    attr_reader renderer: JSONAPI::Serializable::Renderer

    attr_reader success: Proc

    attr_reader error: Proc

    attr_reader params: Hash[Symbol, String | Integer]

    attr_reader request: Hash[Symbol, untyped]

    def initialize: (
        inventory_repo: Repositories::Inventory,
        logger: Logger,
        renderer: JSONAPI::Serializable::Renderer,
        success: Proc,
        error: Proc,
        params: Hash[Symbol, String | Integer],
        request: Hash[Symbol, untyped]
      ) -> InventoryTransferSuggestionsResponse

    def build_inventory_transfer_suggestions_response: () -> Proc
  end
end
