module Services
  class ParametersErrorResponse
    def self.call: (?logger: Logger, ?renderer: JSONAPI::Serializable::Renderer, error: Proc, exception: Errors::ParameterValidationError) -> Proc

    def call: () -> Proc

    private

    attr_reader logger: Logger

    attr_reader renderer: JSONAPI::Serializable::Renderer

    attr_reader error: Proc

    attr_reader exception: Errors::ParameterValidationError

    def initialize: (
        Logger logger,
        JSONAPI::Serializable::Renderer renderer,
        Proc error,
        Errors::ParameterValidationError exception
    ) -> Services::ParametersErrorResponse

    def build_parameter_error_response: () -> Proc
  end
end
