module Services
  class ParametersErrorResponse
    def self.call: (?logger: Logger, ?renderer: JSONAPI::Serializable::Renderer, error: Proc, exception: String) -> untyped

    def call: () -> Proc

    private

    attr_reader logger: Logger

    attr_reader renderer: JSONAPI::Serializable::Renderer

    attr_reader error: Proc

    attr_reader exception: Hash[String | Symbol, untyped]

    def initialize: (Logger logger, JSONAPI::Serializable::Renderer renderer, Proc error, String exception) -> Services::ParametersErrorResponse

    def build_parameter_error_response: () -> Proc
  end
end
