version: '3.8'

x-base-app: &base_app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
      - ".:/app:cached"
      - bundle:/usr/local/bundle
  stdin_open: true
  tty: true
  tmpfs:
    - /tmp    
  env_file:
    - .env

services:
  shoe_store_api:
    <<: *base_app
    entrypoint: ['sh', './entrypoint.sh']
    command: >
      bash -c "RACK_ENV=${RACK_ENV} bundle exec puma --config config/puma.rb"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  websocket:
    <<: *base_app
    command: >
      bash -c "websocketd --port=${WEBSOCKET_PORT} ruby inventory.rb"
    ports:
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    env_file:
      - .env

  shoe_sales_servless_handler:
    <<: *base_app
    entrypoint: ['sh', './entrypoint.sh']
    command: >
      bash -c "ruby server_control.rb run"
    depends_on:
      - websocket
      - postgres
      - rabbitmq
    env_file:
      - .env

  postgres:
    image: 'postgres:${PG_MAJOR}'
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: ${PG_PWD}
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_API_PORT}:${RABBITMQ_API_PORT}
    volumes:
      - "/data"
      - ./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbit/plugins:/usr/lib/rabbitmq/plugins
    env_file:
      - .env
    environment:
      - RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins

  sneakers:
    <<: *base_app
    command: rake sneakers:run --trace
    depends_on:
      - rabbitmq

volumes:
  bundle:
  postgres:

networks:
  default:
      name: dev_ntw
      external: true
