module Business
  module Rules
    class QuantityAlert
      QUANTITY_ALERTS: ::Hash[::String, 0 | ::Range[::Integer]]

      def self.call: (inventory_repo: ::Repositories::Inventory, logger: Logger) -> void

      def call: () -> void

      private

      attr_reader inventory_repo: ::Repositories::Inventory

      attr_reader logger: ::Logger

      def initialize: (inventory_repo: ::Repositories::Inventory, logger: Logger ) -> Business::Rules::QuantityAlert

      def perform_quantity_alerts: () -> void

      def publish_alert: (row: ::Repositories::Inventory) -> JSON
    end
  end
end